### PR TITLE
Added compatibility für plasma 6

### PR DESCRIPTION
**Pull request by Diyou**
These are minimal changes to make the widget work with plasma 6

### CODE REVIEW

**Comment by qewer33** [comment]
Thank you for your PR! Thanks for the typo fixes as well. I don't have a Plasma 6 installation rn so I am unable to test it. Have you tested all the preferences and made sure they work? I will merge it if yes.

**Comment by Diyou** [comment]
It looks like it still needs some bugs fixed. The working area does not resize appropriately with the contents and the the Bold/Italic Buttons aren't changing anything or throwing any errors.

Default Settings:
image

Changing every parameter will look like:
image

**Comment by Diyou** [comment]
When opening the Config Page the FontFamily CheckBoxes are empty but changing Fonts work:
image

One Issue is that the currentIndex gets initiated with a string and when changing the font I get following error:
```shell
file:///.../ClearClock/package/contents/ui/config/configAppearance.qml:75: ReferenceError: clockFontFamilyComboBox is not defined
```

The clock can be recentered on the working area when toggling the background as a workaround.

**Comment by Diyou** [comment]
Guess the only bug remaining is that the clock does not recenter itself automatically.

**Comment by Diyou** [comment]
Everything should work with plasma 6 now.
Also you can probably close #13 with this.

**Comment by xkain** [comment]
Hi,

I tested (thanks for the work), it works on KDE Neon plasma 6 but there is a problem, the size of the plasmoid remains very large even if the content is very small :

Copie d'écran_20240320_110728

**Comment by Diyou** [comment]
Is this different from the plasma 5 behavior? You can resize the background manually after configuring by dragging the corners.

**Comment by Diyou** [comment]
Ah I see its stuck with this as a min size.

**Comment by qewer33** [comment]
@Diyou is this ready to merge?

**Comment by Diyou** [comment]
The layout issues can be addressed in a different pr as this is not plasma 6 related. You can merge this as far as I am concerned.

**Comment by xkain** [comment]
Scroll bar is fixed
Copie d'écran_20240320_173804

**Comment by Diyou** [comment]
@xKain The latest commit should allow you to resize the background after setting small fonts.
There might be an issue with plasma caching the main.qml in which case you'd probably need to relog first.

image

**Comment by xkain** [comment]
Hi,

It hasn't changed for me, the frame is still very big and cannot be smaller and follow the size of the time if it is small : 

Copie d'écran_20240322_184433
ll very large and cannot be smaller and follow the size of the time if it is small.

**Comment by qewer33** [comment]
Thanks a lot for the PR @Diyou! I reviewed and it seems to work well. I'll upload the new version to the KDE Store and give credit to you. I'm also going to make a Reddit post so you can write your username if you have a Reddit account.

**Comment by Diyou** [comment]
You can refer to u/DiyouDev if you want ... certainly not a requirement tho as I'm not using reddit very much.

**Pull request merged**
